package ts.tree;

import ts.Location;
import ts.tree.visit.TreeVisitor;

import java.util.List;

/**
 * node for the root of a block.
 *
 */
public final class Block extends Statement
{
  private List<Statement> list;

  /** Construct an expression statement.
   *
   *  @param loc the source code location of the expression.
   *  @param list list of statements that make up the block
   */
  public Block(final Location loc, final List<Statement> list)
  {
    super(loc);
    this.list = list;
  }

  /** Get the list of statements.
   *
   *  @return the statement list.
   */
  public List<Statement> getList()
  {
    return list;
  }

  /** Apply a visitor to the node.
   *
   *  @param visitor the visitor to apply.
   *
   *  @return the value generated by the visitor.
   */
  @Override public <T> T apply(TreeVisitor<T> visitor)
  {
    return visitor.visit(this);
  }
}

