
package ts.tree;

import ts.Location;
import ts.tree.visit.TreeVisitor;
import ts.tree.type.*;

/**
 * AST control statement node
 *
 */
public final class ControlStatement extends Statement
{
  public static String statement = "";

  public ControlStatement(final Location loc, final String value)
  {
    super(loc);
    this.statement = value;
  }

  /** Apply a visitor to the node.
   *
   *  @param visitor the visitor to apply.
   *
   *  @return the value generated by the visitor.
   */
  @Override public <T> T apply(TreeVisitor<T> visitor)
  {
    return visitor.visit(this);
  }
}

