
package ts.tree;

import ts.Location;
import ts.tree.visit.TreeVisitor;
import ts.tree.type.*;

/**
 * AST empty statement node
 *
 */
public final class EmptyStatement extends Statement
{
  public EmptyStatement(final Location loc)
  {
    super(loc);
  }

  /** Apply a visitor to the node.
   *
   *  @param visitor the visitor to apply.
   *
   *  @return the value generated by the visitor.
   */
  @Override public <T> T apply(TreeVisitor<T> visitor)
  {
    return visitor.visit(this);
  }
}

