
package ts.tree;

import ts.Location;
import ts.tree.visit.TreeVisitor;
import ts.tree.type.UnknownType;

/**
 * AST string literal expression leaf node
 *
 */
public final class NullLiteral extends Expression
{
  /** Construct a Null literal tree node.
   *
   *  @param loc the source code location of the identifier.
   *  @param value the value of the literal.
   */
  public NullLiteral(final Location loc, final String value)
  {
    super(loc);
    this.setType(UnknownType.getInstance());
  }

  /** Get the value of the literal.
   *
   *  @return the value of the literal.
   */
  public Object getValue()
  {
    return null;
  }

  /** Apply a visitor to the node.
   *
   *  @param visitor the visitor to apply.
   *
   *  @return the value generated by the visitor.
   */
  @Override public <T> T apply(TreeVisitor<T> visitor)
  {
    return visitor.visit(this);
  }
}

