package ts.tree;

import ts.Location;
import ts.tree.visit.TreeVisitor;

import java.util.List;

/**
 * node for a property access.
 *
 */
public final class PropAccess extends Expression
{
  private Expression object;
  private String prop;

  /** Construct prop access.
   *
   *  @param loc the source code location of the expression.
   *  @param object name of the object.
   *  @param prop name of the property in object.
   */
  public PropAccess(final Location loc,
      final Expression object, final String prop)
  {
    super(loc);
    this.object = object;
    this.prop = prop;
  }

  /** Get the property name.
   *
   *  @return the property name.
   */
  public Expression getObject()
  {
    return object;
  }

  /** Get the property.
   *
   *  @return the property..
   */
  public String getProp()
  {
    return prop;
  }

  /** Apply a visitor to the node.
   *
   *  @param visitor the visitor to apply.
   *
   *  @return the value generated by the visitor.
   */
  @Override public <T> T apply(TreeVisitor<T> visitor)
  {
    return visitor.visit(this);
  }
}

